name: ci
on:
  workflow_dispatch: #github页面手动触发
  push:
    tags:
      - "v*.*.*.*"
env:
  IMAGE_NAME: openobserve #这是您的镜像名
jobs:
  get-tags:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    outputs:
      tags: ${{ steps.output-id.outputs.v }}
    steps:
      - uses: actions/checkout@v3
      - id: output-id
        run: |
          VERSION=edge
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          echo "v=${VERSION}" >> $GITHUB_OUTPUT

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build && Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./deploy/build/Dockerfile
          push: true
          tags: |
            public.ecr.aws/neiot/${{ env.IMAGE_NAME }}:${{ steps.output-id.outputs.tags }}
            public.ecr.aws/neiot/${{ env.IMAGE_NAME }}:latest